{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {},
   "outputs": [],
   "source": [
    "from selenium import webdriver\n",
    "from selenium.webdriver.common.keys import Keys\n",
    "import time\n",
    "import bs4\n",
    "import pandas as pd"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "metadata": {},
   "outputs": [],
   "source": [
    "keyword = '셀러리'\n",
    "driver = webdriver.Chrome(r'C:\\Users\\jobgs\\Desktop\\CONCAT_SMARTFARM_Project\\DataScience\\SMARTFARM_Project-DataAnalysis_Plant\\chromedriver.exe')\n",
    "driver.get('https://search.shopping.naver.com/search/all?query={}&cat_id=&frm=NVSHATC'.format(keyword))"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 15,
   "metadata": {},
   "outputs": [
    {
     "ename": "WebDriverException",
     "evalue": "Message: chrome not reachable\n  (Session info: chrome=87.0.4280.141)\n",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[1;31mWebDriverException\u001b[0m                        Traceback (most recent call last)",
      "\u001b[1;32m<ipython-input-15-6cbe047c3346>\u001b[0m in \u001b[0;36m<module>\u001b[1;34m\u001b[0m\n\u001b[0;32m      1\u001b[0m \u001b[0mtime\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0msleep\u001b[0m\u001b[1;33m(\u001b[0m\u001b[1;36m5\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[1;32m----> 2\u001b[1;33m \u001b[0mdriver\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mexecute_script\u001b[0m\u001b[1;33m(\u001b[0m\u001b[1;34m\"window.scrollTo(0, document.body.scrollHeight);\"\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0m\u001b[0;32m      3\u001b[0m \u001b[0mtime\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0msleep\u001b[0m\u001b[1;33m(\u001b[0m\u001b[1;36m1\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m      4\u001b[0m \u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m      5\u001b[0m \u001b[1;33m\u001b[0m\u001b[0m\n",
      "\u001b[1;32mC:\\ProgramData\\Anaconda3\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\u001b[0m in \u001b[0;36mexecute_script\u001b[1;34m(self, script, *args)\u001b[0m\n\u001b[0;32m    634\u001b[0m         return self.execute(command, {\n\u001b[0;32m    635\u001b[0m             \u001b[1;34m'script'\u001b[0m\u001b[1;33m:\u001b[0m \u001b[0mscript\u001b[0m\u001b[1;33m,\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[1;32m--> 636\u001b[1;33m             'args': converted_args})['value']\n\u001b[0m\u001b[0;32m    637\u001b[0m \u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m    638\u001b[0m     \u001b[1;32mdef\u001b[0m \u001b[0mexecute_async_script\u001b[0m\u001b[1;33m(\u001b[0m\u001b[0mself\u001b[0m\u001b[1;33m,\u001b[0m \u001b[0mscript\u001b[0m\u001b[1;33m,\u001b[0m \u001b[1;33m*\u001b[0m\u001b[0margs\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m:\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n",
      "\u001b[1;32mC:\\ProgramData\\Anaconda3\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\u001b[0m in \u001b[0;36mexecute\u001b[1;34m(self, driver_command, params)\u001b[0m\n\u001b[0;32m    319\u001b[0m         \u001b[0mresponse\u001b[0m \u001b[1;33m=\u001b[0m \u001b[0mself\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mcommand_executor\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mexecute\u001b[0m\u001b[1;33m(\u001b[0m\u001b[0mdriver_command\u001b[0m\u001b[1;33m,\u001b[0m \u001b[0mparams\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m    320\u001b[0m         \u001b[1;32mif\u001b[0m \u001b[0mresponse\u001b[0m\u001b[1;33m:\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[1;32m--> 321\u001b[1;33m             \u001b[0mself\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0merror_handler\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mcheck_response\u001b[0m\u001b[1;33m(\u001b[0m\u001b[0mresponse\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0m\u001b[0;32m    322\u001b[0m             response['value'] = self._unwrap_value(\n\u001b[0;32m    323\u001b[0m                 response.get('value', None))\n",
      "\u001b[1;32mC:\\ProgramData\\Anaconda3\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\u001b[0m in \u001b[0;36mcheck_response\u001b[1;34m(self, response)\u001b[0m\n\u001b[0;32m    240\u001b[0m                 \u001b[0malert_text\u001b[0m \u001b[1;33m=\u001b[0m \u001b[0mvalue\u001b[0m\u001b[1;33m[\u001b[0m\u001b[1;34m'alert'\u001b[0m\u001b[1;33m]\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mget\u001b[0m\u001b[1;33m(\u001b[0m\u001b[1;34m'text'\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m    241\u001b[0m             \u001b[1;32mraise\u001b[0m \u001b[0mexception_class\u001b[0m\u001b[1;33m(\u001b[0m\u001b[0mmessage\u001b[0m\u001b[1;33m,\u001b[0m \u001b[0mscreen\u001b[0m\u001b[1;33m,\u001b[0m \u001b[0mstacktrace\u001b[0m\u001b[1;33m,\u001b[0m \u001b[0malert_text\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[1;32m--> 242\u001b[1;33m         \u001b[1;32mraise\u001b[0m \u001b[0mexception_class\u001b[0m\u001b[1;33m(\u001b[0m\u001b[0mmessage\u001b[0m\u001b[1;33m,\u001b[0m \u001b[0mscreen\u001b[0m\u001b[1;33m,\u001b[0m \u001b[0mstacktrace\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0m\u001b[0;32m    243\u001b[0m \u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m    244\u001b[0m     \u001b[1;32mdef\u001b[0m \u001b[0m_value_or_default\u001b[0m\u001b[1;33m(\u001b[0m\u001b[0mself\u001b[0m\u001b[1;33m,\u001b[0m \u001b[0mobj\u001b[0m\u001b[1;33m,\u001b[0m \u001b[0mkey\u001b[0m\u001b[1;33m,\u001b[0m \u001b[0mdefault\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m:\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n",
      "\u001b[1;31mWebDriverException\u001b[0m: Message: chrome not reachable\n  (Session info: chrome=87.0.4280.141)\n"
     ]
    }
   ],
   "source": [
    "time.sleep(5)\n",
    "driver.execute_script(\"window.scrollTo(0, document.body.scrollHeight);\")\n",
    "time.sleep(1)\n",
    "\n",
    "\n",
    "item_source = bs4.BeautifulSoup(driver.page_source, 'lxml')\n",
    "item_list = item_source.select('div.basicList_info_area__17Xyo')\n",
    "item_list"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 8,
   "metadata": {},
   "outputs": [],
   "source": [
    "title_list = []\n",
    "price_list = []\n",
    "review_list = []\n",
    "buy_list = []\n",
    "\n",
    "for item in item_list:\n",
    "    title = item.select_one('a').text.replace('\\n', '')\n",
    "    price = item.select_one('span.price_num__2WUXn').text\n",
    "    ReviewAndBuy = item.select('a.basicList_etc__2uAYO > em')\n",
    "    try:\n",
    "        review = ReviewAndBuy[0].text + '개'\n",
    "    except IndexError:\n",
    "        review = '없음'\n",
    "    \n",
    "    try:\n",
    "        buy = ReviewAndBuy[1].text + '개'\n",
    "    except IndexError:\n",
    "        buy = '없음'\n",
    "        \n",
    "    title_list.append(title)\n",
    "    price_list.append(price)\n",
    "    review_list.append(review)\n",
    "    buy_list.append(buy)\n",
    "#print(review_list)\n",
    "#print(title_list, price_list, review_list, buy_list)\n",
    "df = pd.DataFrame({'상품명':title_list, '가격':price_list, '리뷰수':review_list, '구매건수':buy_list})"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 9,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>상품명</th>\n",
       "      <th>가격</th>\n",
       "      <th>리뷰수</th>\n",
       "      <th>구매건수</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>절단 셀러리 500g</td>\n",
       "      <td>2,990원</td>\n",
       "      <td>없음</td>\n",
       "      <td>없음</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1</th>\n",
       "      <td>친환경 무농약 셀러리 3kg/5kg</td>\n",
       "      <td>18,900원</td>\n",
       "      <td>399개</td>\n",
       "      <td>88개</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2</th>\n",
       "      <td>GAP 건강하게 재배된 샐러리 셀러리</td>\n",
       "      <td>5,900원</td>\n",
       "      <td>없음</td>\n",
       "      <td>없음</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>3</th>\n",
       "      <td>국내산 샐러리 2kg 5kg</td>\n",
       "      <td>5,500원</td>\n",
       "      <td>2,187개</td>\n",
       "      <td>1,102개</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4</th>\n",
       "      <td>[산지직송] 유기농 무농약 주스용 즙용 레드 비트 콜라비 신선초 생 파슬리 샐러리 케일</td>\n",
       "      <td>7,900원</td>\n",
       "      <td>4,186개</td>\n",
       "      <td>1,523개</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>5</th>\n",
       "      <td>샐러리 3kg 5kg 10kg 셀러리</td>\n",
       "      <td>11,900원</td>\n",
       "      <td>1,731개</td>\n",
       "      <td>166개</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>6</th>\n",
       "      <td>유기농 생 신선초 케일 샐러리 비트 1kg 주스용 쥬스용 착즙 녹즙 즙용 무농약 재료</td>\n",
       "      <td>4,900원</td>\n",
       "      <td>298개</td>\n",
       "      <td>513개</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>7</th>\n",
       "      <td>샐러리 (1KG) 셀러리 CELERY 샐러드</td>\n",
       "      <td>4,000원</td>\n",
       "      <td>980개</td>\n",
       "      <td>231개</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>8</th>\n",
       "      <td>손질샐러리 1팩 300g / 500g 스틱샐러리</td>\n",
       "      <td>4,900원</td>\n",
       "      <td>457개</td>\n",
       "      <td>215개</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>9</th>\n",
       "      <td>[산지직송] 친환경 무농약 셀러리 (재 주문이 / 많은) 최상품 샐러리 3kg 5k...</td>\n",
       "      <td>18,500원</td>\n",
       "      <td>71개</td>\n",
       "      <td>139개</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>10</th>\n",
       "      <td>무농약 셀러리 샐러리 양 미나리 3kg</td>\n",
       "      <td>19,900원</td>\n",
       "      <td>368개</td>\n",
       "      <td>32개</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>11</th>\n",
       "      <td>당일수확 유기농 샐러리 신선초 500g 1kg 녹즙용 주스용 녹즙 채소 명일엽 셀러리</td>\n",
       "      <td>7,900원</td>\n",
       "      <td>26개</td>\n",
       "      <td>58개</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>12</th>\n",
       "      <td>친환경 유기농 신선초(명일엽) 녹즙용 1kg/유기농 케일/무농약 셀러리</td>\n",
       "      <td>8,900원</td>\n",
       "      <td>267개</td>\n",
       "      <td>418개</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>13</th>\n",
       "      <td>강원도 홍천 아삭한 유기농 샐러리 500G / 주문시 수확 당일발송</td>\n",
       "      <td>3,500원</td>\n",
       "      <td>236개</td>\n",
       "      <td>49개</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>14</th>\n",
       "      <td>[삼현농장] 친환경 무농약 다용도 셀러리 2kg / 당일수확발송 (오전10시 주문분까지)</td>\n",
       "      <td>12,900원</td>\n",
       "      <td>3,637개</td>\n",
       "      <td>1,332개</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>15</th>\n",
       "      <td>유기농 샐러리 500g 셀러리</td>\n",
       "      <td>4,900원</td>\n",
       "      <td>172개</td>\n",
       "      <td>64개</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>16</th>\n",
       "      <td>공철표님의 싱싱한 무농약 셀러리/샐러리/양미나리 3kg</td>\n",
       "      <td>19,900원</td>\n",
       "      <td>368개</td>\n",
       "      <td>32개</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>17</th>\n",
       "      <td>친환경 무농약 셀러리 3kg/5kg/양배추</td>\n",
       "      <td>18,900원</td>\n",
       "      <td>399개</td>\n",
       "      <td>88개</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>18</th>\n",
       "      <td>[프레시팜] 국내산 셀러리 즙용 10kg 1박스</td>\n",
       "      <td>9,900원</td>\n",
       "      <td>3개</td>\n",
       "      <td>없음</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>19</th>\n",
       "      <td>샐러리 10kg</td>\n",
       "      <td>24,800원</td>\n",
       "      <td>24개</td>\n",
       "      <td>55개</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>20</th>\n",
       "      <td>채소습관 샐러리 스틱 100g x5팩</td>\n",
       "      <td>20,800원</td>\n",
       "      <td>153개</td>\n",
       "      <td>없음</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>21</th>\n",
       "      <td>FRESH 새벽에 수확한 국내산 유기농 무농약 케일 신선초 샐러리 생 파슬리</td>\n",
       "      <td>7,900원</td>\n",
       "      <td>117개</td>\n",
       "      <td>없음</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>22</th>\n",
       "      <td>유기농 케일 신선초 비트 1kg 샐러리 500g 주스 쥬스 용 착즙 녹즙 즙 무농약 재료</td>\n",
       "      <td>4,900원</td>\n",
       "      <td>26개</td>\n",
       "      <td>85개</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>23</th>\n",
       "      <td>유기농 무농약 샐러리 1kg 2kg</td>\n",
       "      <td>7,900원</td>\n",
       "      <td>4,184개</td>\n",
       "      <td>1,532개</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>24</th>\n",
       "      <td>유기농 녹즙채소 녹즙재료 6종 즙케일 샐러리 신선초 주스용 당근 흠집사과 토마토, ...</td>\n",
       "      <td>3,500원</td>\n",
       "      <td>2,221개</td>\n",
       "      <td>1,609개</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>25</th>\n",
       "      <td>[우리가락]샐러드용샐러리 한단</td>\n",
       "      <td>4,100원</td>\n",
       "      <td>없음</td>\n",
       "      <td>없음</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>26</th>\n",
       "      <td>셀러리 샐러리 1kg 국산 1봉 1단 celery</td>\n",
       "      <td>3,500원</td>\n",
       "      <td>48개</td>\n",
       "      <td>32개</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>27</th>\n",
       "      <td>절단 셀러리 500g</td>\n",
       "      <td>2,990원</td>\n",
       "      <td>3,977개</td>\n",
       "      <td>없음</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>28</th>\n",
       "      <td>[야채마루] 셀러리 샐러리</td>\n",
       "      <td>5,500원</td>\n",
       "      <td>524개</td>\n",
       "      <td>없음</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>29</th>\n",
       "      <td>유기농 샐러리 500g 셀러리</td>\n",
       "      <td>4,900원</td>\n",
       "      <td>172개</td>\n",
       "      <td>62개</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>30</th>\n",
       "      <td>샐러리(봉)</td>\n",
       "      <td>2,480원</td>\n",
       "      <td>3,650개</td>\n",
       "      <td>없음</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>31</th>\n",
       "      <td>샐러리(봉)</td>\n",
       "      <td>2,480원</td>\n",
       "      <td>3,649개</td>\n",
       "      <td>없음</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>32</th>\n",
       "      <td>[야채마루] 셀러리 샐러리 2kg   3kg   5kg - 신선한 셀러리를 당일배송으로</td>\n",
       "      <td>5,500원</td>\n",
       "      <td>229개</td>\n",
       "      <td>없음</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>33</th>\n",
       "      <td>[팜포크] 다이어트에 좋은 친환경 무농약 샐러리 3kg, 5kg 샐러리 농장 산지직송</td>\n",
       "      <td>17,900원</td>\n",
       "      <td>없음</td>\n",
       "      <td>없음</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>34</th>\n",
       "      <td>산정마을 국내산 샐러리 3kg</td>\n",
       "      <td>7,900원</td>\n",
       "      <td>499개</td>\n",
       "      <td>없음</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>35</th>\n",
       "      <td>싱싱한 샐러리</td>\n",
       "      <td>5,500원</td>\n",
       "      <td>454개</td>\n",
       "      <td>없음</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>36</th>\n",
       "      <td>당근샐러리스틱 간편야채 380g</td>\n",
       "      <td>4,570원</td>\n",
       "      <td>1개</td>\n",
       "      <td>없음</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>37</th>\n",
       "      <td>유기농 셀러리 1kg, 2kg 케일, 신선초, 명일엽, 녹즙채소</td>\n",
       "      <td>11,900원</td>\n",
       "      <td>14개</td>\n",
       "      <td>5개</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>38</th>\n",
       "      <td>[조아쌈]무농약 녹즙케일 녹즙샐러리 짱아찌용 샐러리 2kg 당일수확, 당일배송</td>\n",
       "      <td>12,000원</td>\n",
       "      <td>3개</td>\n",
       "      <td>9개</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>39</th>\n",
       "      <td>샐러리 (Celery) 1포기 1kg 내외</td>\n",
       "      <td>5,000원</td>\n",
       "      <td>42개</td>\n",
       "      <td>110개</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>40</th>\n",
       "      <td>공철표님의 무농약 셀러리/샐러리/양미나리 5kg 3kg</td>\n",
       "      <td>18,620원</td>\n",
       "      <td>12개</td>\n",
       "      <td>없음</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>41</th>\n",
       "      <td>행복농산 싱싱한 샐러리</td>\n",
       "      <td>11,900원</td>\n",
       "      <td>79개</td>\n",
       "      <td>없음</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>42</th>\n",
       "      <td>유기농 녹즙 용 케일 1Kg (샐러리 신선초 비트 당근)</td>\n",
       "      <td>5,030원</td>\n",
       "      <td>19개</td>\n",
       "      <td>없음</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>43</th>\n",
       "      <td>권정기님의 친환경 유기농 녹즙용 케일 비트 신선초 셀러리 당근 밀싹 보리싹</td>\n",
       "      <td>4,900원</td>\n",
       "      <td>49개</td>\n",
       "      <td>없음</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>44</th>\n",
       "      <td>샐러리 1단 1kg</td>\n",
       "      <td>6,300원</td>\n",
       "      <td>110개</td>\n",
       "      <td>24개</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>45</th>\n",
       "      <td>셀러리 녹즙 샐러리 5kg 3kg 2kg내외</td>\n",
       "      <td>24,900원</td>\n",
       "      <td>85개</td>\n",
       "      <td>3개</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "</div>"
      ],
      "text/plain": [
       "                                                  상품명       가격     리뷰수    구매건수\n",
       "0                                         절단 셀러리 500g   2,990원      없음      없음\n",
       "1                                 친환경 무농약 셀러리 3kg/5kg  18,900원    399개     88개\n",
       "2                                GAP 건강하게 재배된 샐러리 셀러리   5,900원      없음      없음\n",
       "3                                     국내산 샐러리 2kg 5kg   5,500원  2,187개  1,102개\n",
       "4    [산지직송] 유기농 무농약 주스용 즙용 레드 비트 콜라비 신선초 생 파슬리 샐러리 케일   7,900원  4,186개  1,523개\n",
       "5                                샐러리 3kg 5kg 10kg 셀러리  11,900원  1,731개    166개\n",
       "6     유기농 생 신선초 케일 샐러리 비트 1kg 주스용 쥬스용 착즙 녹즙 즙용 무농약 재료   4,900원    298개    513개\n",
       "7                            샐러리 (1KG) 셀러리 CELERY 샐러드   4,000원    980개    231개\n",
       "8                          손질샐러리 1팩 300g / 500g 스틱샐러리   4,900원    457개    215개\n",
       "9   [산지직송] 친환경 무농약 셀러리 (재 주문이 / 많은) 최상품 샐러리 3kg 5k...  18,500원     71개    139개\n",
       "10                              무농약 셀러리 샐러리 양 미나리 3kg  19,900원    368개     32개\n",
       "11    당일수확 유기농 샐러리 신선초 500g 1kg 녹즙용 주스용 녹즙 채소 명일엽 셀러리   7,900원     26개     58개\n",
       "12            친환경 유기농 신선초(명일엽) 녹즙용 1kg/유기농 케일/무농약 셀러리   8,900원    267개    418개\n",
       "13              강원도 홍천 아삭한 유기농 샐러리 500G / 주문시 수확 당일발송   3,500원    236개     49개\n",
       "14  [삼현농장] 친환경 무농약 다용도 셀러리 2kg / 당일수확발송 (오전10시 주문분까지)  12,900원  3,637개  1,332개\n",
       "15                                   유기농 샐러리 500g 셀러리   4,900원    172개     64개\n",
       "16                     공철표님의 싱싱한 무농약 셀러리/샐러리/양미나리 3kg  19,900원    368개     32개\n",
       "17                            친환경 무농약 셀러리 3kg/5kg/양배추  18,900원    399개     88개\n",
       "18                         [프레시팜] 국내산 셀러리 즙용 10kg 1박스   9,900원      3개      없음\n",
       "19                                           샐러리 10kg  24,800원     24개     55개\n",
       "20                               채소습관 샐러리 스틱 100g x5팩  20,800원    153개      없음\n",
       "21         FRESH 새벽에 수확한 국내산 유기농 무농약 케일 신선초 샐러리 생 파슬리   7,900원    117개      없음\n",
       "22  유기농 케일 신선초 비트 1kg 샐러리 500g 주스 쥬스 용 착즙 녹즙 즙 무농약 재료   4,900원     26개     85개\n",
       "23                                유기농 무농약 샐러리 1kg 2kg   7,900원  4,184개  1,532개\n",
       "24  유기농 녹즙채소 녹즙재료 6종 즙케일 샐러리 신선초 주스용 당근 흠집사과 토마토, ...   3,500원  2,221개  1,609개\n",
       "25                                   [우리가락]샐러드용샐러리 한단   4,100원      없음      없음\n",
       "26                        셀러리 샐러리 1kg 국산 1봉 1단 celery   3,500원     48개     32개\n",
       "27                                        절단 셀러리 500g   2,990원  3,977개      없음\n",
       "28                                     [야채마루] 셀러리 샐러리   5,500원    524개      없음\n",
       "29                                   유기농 샐러리 500g 셀러리   4,900원    172개     62개\n",
       "30                                             샐러리(봉)   2,480원  3,650개      없음\n",
       "31                                             샐러리(봉)   2,480원  3,649개      없음\n",
       "32   [야채마루] 셀러리 샐러리 2kg   3kg   5kg - 신선한 셀러리를 당일배송으로   5,500원    229개      없음\n",
       "33    [팜포크] 다이어트에 좋은 친환경 무농약 샐러리 3kg, 5kg 샐러리 농장 산지직송  17,900원      없음      없음\n",
       "34                                   산정마을 국내산 샐러리 3kg   7,900원    499개      없음\n",
       "35                                            싱싱한 샐러리   5,500원    454개      없음\n",
       "36                                  당근샐러리스틱 간편야채 380g   4,570원      1개      없음\n",
       "37                유기농 셀러리 1kg, 2kg 케일, 신선초, 명일엽, 녹즙채소  11,900원     14개      5개\n",
       "38        [조아쌈]무농약 녹즙케일 녹즙샐러리 짱아찌용 샐러리 2kg 당일수확, 당일배송  12,000원      3개      9개\n",
       "39                            샐러리 (Celery) 1포기 1kg 내외   5,000원     42개    110개\n",
       "40                     공철표님의 무농약 셀러리/샐러리/양미나리 5kg 3kg  18,620원     12개      없음\n",
       "41                                       행복농산 싱싱한 샐러리  11,900원     79개      없음\n",
       "42                    유기농 녹즙 용 케일 1Kg (샐러리 신선초 비트 당근)   5,030원     19개      없음\n",
       "43          권정기님의 친환경 유기농 녹즙용 케일 비트 신선초 셀러리 당근 밀싹 보리싹   4,900원     49개      없음\n",
       "44                                         샐러리 1단 1kg   6,300원    110개     24개\n",
       "45                           셀러리 녹즙 샐러리 5kg 3kg 2kg내외  24,900원     85개      3개"
      ]
     },
     "execution_count": 9,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "df"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 10,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>상품명</th>\n",
       "      <th>가격</th>\n",
       "      <th>리뷰수</th>\n",
       "      <th>구매건수</th>\n",
       "      <th>무게당 가격</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>절단 셀러리 500g</td>\n",
       "      <td>2,990원</td>\n",
       "      <td>없음</td>\n",
       "      <td>없음</td>\n",
       "      <td>500g</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1</th>\n",
       "      <td>친환경 무농약 셀러리 3kg/5kg</td>\n",
       "      <td>18,900원</td>\n",
       "      <td>399개</td>\n",
       "      <td>88개</td>\n",
       "      <td>3kg</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2</th>\n",
       "      <td>국내산 샐러리 2kg 5kg</td>\n",
       "      <td>5,500원</td>\n",
       "      <td>2,187개</td>\n",
       "      <td>1,102개</td>\n",
       "      <td>2kg</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>3</th>\n",
       "      <td>샐러리 3kg 5kg 10kg 셀러리</td>\n",
       "      <td>11,900원</td>\n",
       "      <td>1,731개</td>\n",
       "      <td>166개</td>\n",
       "      <td>3kg</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4</th>\n",
       "      <td>유기농 생 신선초 케일 샐러리 비트 1kg 주스용 쥬스용 착즙 녹즙 즙용 무농약 재료</td>\n",
       "      <td>4,900원</td>\n",
       "      <td>298개</td>\n",
       "      <td>513개</td>\n",
       "      <td>1kg</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>5</th>\n",
       "      <td>샐러리 (1KG) 셀러리 CELERY 샐러드</td>\n",
       "      <td>4,000원</td>\n",
       "      <td>980개</td>\n",
       "      <td>231개</td>\n",
       "      <td>1KG</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>6</th>\n",
       "      <td>손질샐러리 1팩 300g / 500g 스틱샐러리</td>\n",
       "      <td>4,900원</td>\n",
       "      <td>457개</td>\n",
       "      <td>215개</td>\n",
       "      <td>300g</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>7</th>\n",
       "      <td>[산지직송] 친환경 무농약 셀러리 (재 주문이 / 많은) 최상품 샐러리 3kg 5k...</td>\n",
       "      <td>18,500원</td>\n",
       "      <td>71개</td>\n",
       "      <td>139개</td>\n",
       "      <td>3kg</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>8</th>\n",
       "      <td>무농약 셀러리 샐러리 양 미나리 3kg</td>\n",
       "      <td>19,900원</td>\n",
       "      <td>368개</td>\n",
       "      <td>32개</td>\n",
       "      <td>3kg</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>9</th>\n",
       "      <td>당일수확 유기농 샐러리 신선초 500g 1kg 녹즙용 주스용 녹즙 채소 명일엽 셀러리</td>\n",
       "      <td>7,900원</td>\n",
       "      <td>26개</td>\n",
       "      <td>58개</td>\n",
       "      <td>500g</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>10</th>\n",
       "      <td>친환경 유기농 신선초(명일엽) 녹즙용 1kg/유기농 케일/무농약 셀러리</td>\n",
       "      <td>8,900원</td>\n",
       "      <td>267개</td>\n",
       "      <td>418개</td>\n",
       "      <td>1kg</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>11</th>\n",
       "      <td>[삼현농장] 친환경 무농약 다용도 셀러리 2kg / 당일수확발송 (오전10시 주문분까지)</td>\n",
       "      <td>12,900원</td>\n",
       "      <td>3,637개</td>\n",
       "      <td>1,332개</td>\n",
       "      <td>2kg</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>12</th>\n",
       "      <td>유기농 샐러리 500g 셀러리</td>\n",
       "      <td>4,900원</td>\n",
       "      <td>172개</td>\n",
       "      <td>64개</td>\n",
       "      <td>500g</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>13</th>\n",
       "      <td>공철표님의 싱싱한 무농약 셀러리/샐러리/양미나리 3kg</td>\n",
       "      <td>19,900원</td>\n",
       "      <td>368개</td>\n",
       "      <td>32개</td>\n",
       "      <td>3kg</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>14</th>\n",
       "      <td>친환경 무농약 셀러리 3kg/5kg/양배추</td>\n",
       "      <td>18,900원</td>\n",
       "      <td>399개</td>\n",
       "      <td>88개</td>\n",
       "      <td>3kg</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>15</th>\n",
       "      <td>[프레시팜] 국내산 셀러리 즙용 10kg 1박스</td>\n",
       "      <td>9,900원</td>\n",
       "      <td>3개</td>\n",
       "      <td>없음</td>\n",
       "      <td>10kg</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>16</th>\n",
       "      <td>샐러리 10kg</td>\n",
       "      <td>24,800원</td>\n",
       "      <td>24개</td>\n",
       "      <td>55개</td>\n",
       "      <td>10kg</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>17</th>\n",
       "      <td>채소습관 샐러리 스틱 100g x5팩</td>\n",
       "      <td>20,800원</td>\n",
       "      <td>153개</td>\n",
       "      <td>없음</td>\n",
       "      <td>100g</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>18</th>\n",
       "      <td>유기농 케일 신선초 비트 1kg 샐러리 500g 주스 쥬스 용 착즙 녹즙 즙 무농약 재료</td>\n",
       "      <td>4,900원</td>\n",
       "      <td>26개</td>\n",
       "      <td>85개</td>\n",
       "      <td>1kg</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>19</th>\n",
       "      <td>유기농 무농약 샐러리 1kg 2kg</td>\n",
       "      <td>7,900원</td>\n",
       "      <td>4,184개</td>\n",
       "      <td>1,532개</td>\n",
       "      <td>1kg</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>20</th>\n",
       "      <td>셀러리 샐러리 1kg 국산 1봉 1단 celery</td>\n",
       "      <td>3,500원</td>\n",
       "      <td>48개</td>\n",
       "      <td>32개</td>\n",
       "      <td>1kg</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>21</th>\n",
       "      <td>절단 셀러리 500g</td>\n",
       "      <td>2,990원</td>\n",
       "      <td>3,977개</td>\n",
       "      <td>없음</td>\n",
       "      <td>500g</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>22</th>\n",
       "      <td>유기농 샐러리 500g 셀러리</td>\n",
       "      <td>4,900원</td>\n",
       "      <td>172개</td>\n",
       "      <td>62개</td>\n",
       "      <td>500g</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>23</th>\n",
       "      <td>[야채마루] 셀러리 샐러리 2kg   3kg   5kg - 신선한 셀러리를 당일배송으로</td>\n",
       "      <td>5,500원</td>\n",
       "      <td>229개</td>\n",
       "      <td>없음</td>\n",
       "      <td>2kg</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>24</th>\n",
       "      <td>[팜포크] 다이어트에 좋은 친환경 무농약 샐러리 3kg, 5kg 샐러리 농장 산지직송</td>\n",
       "      <td>17,900원</td>\n",
       "      <td>없음</td>\n",
       "      <td>없음</td>\n",
       "      <td>3kg</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>25</th>\n",
       "      <td>산정마을 국내산 샐러리 3kg</td>\n",
       "      <td>7,900원</td>\n",
       "      <td>499개</td>\n",
       "      <td>없음</td>\n",
       "      <td>3kg</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>26</th>\n",
       "      <td>당근샐러리스틱 간편야채 380g</td>\n",
       "      <td>4,570원</td>\n",
       "      <td>1개</td>\n",
       "      <td>없음</td>\n",
       "      <td>380g</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>27</th>\n",
       "      <td>유기농 셀러리 1kg, 2kg 케일, 신선초, 명일엽, 녹즙채소</td>\n",
       "      <td>11,900원</td>\n",
       "      <td>14개</td>\n",
       "      <td>5개</td>\n",
       "      <td>1kg</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>28</th>\n",
       "      <td>[조아쌈]무농약 녹즙케일 녹즙샐러리 짱아찌용 샐러리 2kg 당일수확, 당일배송</td>\n",
       "      <td>12,000원</td>\n",
       "      <td>3개</td>\n",
       "      <td>9개</td>\n",
       "      <td>2kg</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>29</th>\n",
       "      <td>샐러리 (Celery) 1포기 1kg 내외</td>\n",
       "      <td>5,000원</td>\n",
       "      <td>42개</td>\n",
       "      <td>110개</td>\n",
       "      <td>1kg</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>30</th>\n",
       "      <td>공철표님의 무농약 셀러리/샐러리/양미나리 5kg 3kg</td>\n",
       "      <td>18,620원</td>\n",
       "      <td>12개</td>\n",
       "      <td>없음</td>\n",
       "      <td>5kg</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>31</th>\n",
       "      <td>유기농 녹즙 용 케일 1Kg (샐러리 신선초 비트 당근)</td>\n",
       "      <td>5,030원</td>\n",
       "      <td>19개</td>\n",
       "      <td>없음</td>\n",
       "      <td>1Kg</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>32</th>\n",
       "      <td>샐러리 1단 1kg</td>\n",
       "      <td>6,300원</td>\n",
       "      <td>110개</td>\n",
       "      <td>24개</td>\n",
       "      <td>1kg</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>33</th>\n",
       "      <td>셀러리 녹즙 샐러리 5kg 3kg 2kg내외</td>\n",
       "      <td>24,900원</td>\n",
       "      <td>85개</td>\n",
       "      <td>3개</td>\n",
       "      <td>5kg</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "</div>"
      ],
      "text/plain": [
       "                                                  상품명       가격     리뷰수  \\\n",
       "0                                         절단 셀러리 500g   2,990원      없음   \n",
       "1                                 친환경 무농약 셀러리 3kg/5kg  18,900원    399개   \n",
       "2                                     국내산 샐러리 2kg 5kg   5,500원  2,187개   \n",
       "3                                샐러리 3kg 5kg 10kg 셀러리  11,900원  1,731개   \n",
       "4     유기농 생 신선초 케일 샐러리 비트 1kg 주스용 쥬스용 착즙 녹즙 즙용 무농약 재료   4,900원    298개   \n",
       "5                            샐러리 (1KG) 셀러리 CELERY 샐러드   4,000원    980개   \n",
       "6                          손질샐러리 1팩 300g / 500g 스틱샐러리   4,900원    457개   \n",
       "7   [산지직송] 친환경 무농약 셀러리 (재 주문이 / 많은) 최상품 샐러리 3kg 5k...  18,500원     71개   \n",
       "8                               무농약 셀러리 샐러리 양 미나리 3kg  19,900원    368개   \n",
       "9     당일수확 유기농 샐러리 신선초 500g 1kg 녹즙용 주스용 녹즙 채소 명일엽 셀러리   7,900원     26개   \n",
       "10            친환경 유기농 신선초(명일엽) 녹즙용 1kg/유기농 케일/무농약 셀러리   8,900원    267개   \n",
       "11  [삼현농장] 친환경 무농약 다용도 셀러리 2kg / 당일수확발송 (오전10시 주문분까지)  12,900원  3,637개   \n",
       "12                                   유기농 샐러리 500g 셀러리   4,900원    172개   \n",
       "13                     공철표님의 싱싱한 무농약 셀러리/샐러리/양미나리 3kg  19,900원    368개   \n",
       "14                            친환경 무농약 셀러리 3kg/5kg/양배추  18,900원    399개   \n",
       "15                         [프레시팜] 국내산 셀러리 즙용 10kg 1박스   9,900원      3개   \n",
       "16                                           샐러리 10kg  24,800원     24개   \n",
       "17                               채소습관 샐러리 스틱 100g x5팩  20,800원    153개   \n",
       "18  유기농 케일 신선초 비트 1kg 샐러리 500g 주스 쥬스 용 착즙 녹즙 즙 무농약 재료   4,900원     26개   \n",
       "19                                유기농 무농약 샐러리 1kg 2kg   7,900원  4,184개   \n",
       "20                        셀러리 샐러리 1kg 국산 1봉 1단 celery   3,500원     48개   \n",
       "21                                        절단 셀러리 500g   2,990원  3,977개   \n",
       "22                                   유기농 샐러리 500g 셀러리   4,900원    172개   \n",
       "23   [야채마루] 셀러리 샐러리 2kg   3kg   5kg - 신선한 셀러리를 당일배송으로   5,500원    229개   \n",
       "24    [팜포크] 다이어트에 좋은 친환경 무농약 샐러리 3kg, 5kg 샐러리 농장 산지직송  17,900원      없음   \n",
       "25                                   산정마을 국내산 샐러리 3kg   7,900원    499개   \n",
       "26                                  당근샐러리스틱 간편야채 380g   4,570원      1개   \n",
       "27                유기농 셀러리 1kg, 2kg 케일, 신선초, 명일엽, 녹즙채소  11,900원     14개   \n",
       "28        [조아쌈]무농약 녹즙케일 녹즙샐러리 짱아찌용 샐러리 2kg 당일수확, 당일배송  12,000원      3개   \n",
       "29                            샐러리 (Celery) 1포기 1kg 내외   5,000원     42개   \n",
       "30                     공철표님의 무농약 셀러리/샐러리/양미나리 5kg 3kg  18,620원     12개   \n",
       "31                    유기농 녹즙 용 케일 1Kg (샐러리 신선초 비트 당근)   5,030원     19개   \n",
       "32                                         샐러리 1단 1kg   6,300원    110개   \n",
       "33                           셀러리 녹즙 샐러리 5kg 3kg 2kg내외  24,900원     85개   \n",
       "\n",
       "      구매건수 무게당 가격  \n",
       "0       없음   500g  \n",
       "1      88개    3kg  \n",
       "2   1,102개    2kg  \n",
       "3     166개    3kg  \n",
       "4     513개    1kg  \n",
       "5     231개    1KG  \n",
       "6     215개   300g  \n",
       "7     139개    3kg  \n",
       "8      32개    3kg  \n",
       "9      58개   500g  \n",
       "10    418개    1kg  \n",
       "11  1,332개    2kg  \n",
       "12     64개   500g  \n",
       "13     32개    3kg  \n",
       "14     88개    3kg  \n",
       "15      없음   10kg  \n",
       "16     55개   10kg  \n",
       "17      없음   100g  \n",
       "18     85개    1kg  \n",
       "19  1,532개    1kg  \n",
       "20     32개    1kg  \n",
       "21      없음   500g  \n",
       "22     62개   500g  \n",
       "23      없음    2kg  \n",
       "24      없음    3kg  \n",
       "25      없음    3kg  \n",
       "26      없음   380g  \n",
       "27      5개    1kg  \n",
       "28      9개    2kg  \n",
       "29    110개    1kg  \n",
       "30      없음    5kg  \n",
       "31      없음    1Kg  \n",
       "32     24개    1kg  \n",
       "33      3개    5kg  "
      ]
     },
     "execution_count": 10,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "gram_tmp = df.상품명.str.extract('(\\d+g|\\d+kg|\\d+Kg|\\d+KG)')\n",
    "df['무게당 가격'] = gram_tmp.dropna()\n",
    "df1 = df.dropna()\n",
    "df1.reset_index(inplace=True)\n",
    "del df1['index']\n",
    "df1"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 14,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "4\n",
      "6\n",
      "7\n",
      "9\n",
      "10\n",
      "15\n",
      "17\n",
      "18\n",
      "27\n",
      "28\n",
      "31\n",
      "33\n"
     ]
    }
   ],
   "source": [
    "for i in range(len(df1)):\n",
    "    tmp = df1.loc[i][0]\n",
    "    if '즙' in tmp or '주스' in tmp or '쥬스' in tmp or '팩' in tmp:\n",
    "        print(df1.index[i])\n",
    "        df1.drop(df1.index[i], inplace=True)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 11,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "[500, 3000, 2000, 3000, 1000, 1000, 300, 3000, 3000, 500, 1000, 2000, 500, 3000, 3000, 10000, 10000, 100, 1000, 1000, 1000, 500, 500, 2000, 3000, 3000, 380, 1000, 2000, 1000, 5000, 1000, 1000, 5000]\n"
     ]
    }
   ],
   "source": [
    "# 무게만 추출\n",
    "gram_list = []\n",
    "for i in range(len(df1)):\n",
    "    tmp = df1.loc[i][4]\n",
    "    if 'kg' in tmp:\n",
    "        wei = tmp.split('kg')\n",
    "        res = int(wei[0])*1000\n",
    "    elif 'Kg' in tmp:\n",
    "        wei = tmp.split('Kg')\n",
    "        res = int(wei[0])*1000\n",
    "    elif 'KG' in tmp:\n",
    "        wei = tmp.split('KG')\n",
    "        res = int(wei[0])*1000\n",
    "    elif 'g' in tmp:\n",
    "        wei = tmp.split('g')\n",
    "        res = int(wei[0])\n",
    "    gram_list.append(res)\n",
    "print(gram_list)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 12,
   "metadata": {},
   "outputs": [],
   "source": [
    "# 가격 추출\n",
    "plist = []\n",
    "for i in range(len(df1)):\n",
    "    tmp = df1.loc[i][1]\n",
    "    tmp1 = tmp.split('원')\n",
    "    tmp2 = tmp1[0].split(',')\n",
    "    tmp3 = ''.join(tmp2)\n",
    "    plist.append(int(tmp3))"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 13,
   "metadata": {
    "scrolled": false
   },
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "C:\\Users\\jobgs\\AppData\\Roaming\\Python\\Python37\\site-packages\\ipykernel_launcher.py:6: SettingWithCopyWarning: \n",
      "A value is trying to be set on a copy of a slice from a DataFrame.\n",
      "Try using .loc[row_indexer,col_indexer] = value instead\n",
      "\n",
      "See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy\n",
      "  \n"
     ]
    },
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>상품명</th>\n",
       "      <th>가격</th>\n",
       "      <th>리뷰수</th>\n",
       "      <th>구매건수</th>\n",
       "      <th>가격/g</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>절단 셀러리 500g</td>\n",
       "      <td>2,990원</td>\n",
       "      <td>없음</td>\n",
       "      <td>없음</td>\n",
       "      <td>5원/g</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1</th>\n",
       "      <td>친환경 무농약 셀러리 3kg/5kg</td>\n",
       "      <td>18,900원</td>\n",
       "      <td>399개</td>\n",
       "      <td>88개</td>\n",
       "      <td>6원/g</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2</th>\n",
       "      <td>국내산 샐러리 2kg 5kg</td>\n",
       "      <td>5,500원</td>\n",
       "      <td>2,187개</td>\n",
       "      <td>1,102개</td>\n",
       "      <td>2원/g</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>3</th>\n",
       "      <td>샐러리 3kg 5kg 10kg 셀러리</td>\n",
       "      <td>11,900원</td>\n",
       "      <td>1,731개</td>\n",
       "      <td>166개</td>\n",
       "      <td>3원/g</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4</th>\n",
       "      <td>유기농 생 신선초 케일 샐러리 비트 1kg 주스용 쥬스용 착즙 녹즙 즙용 무농약 재료</td>\n",
       "      <td>4,900원</td>\n",
       "      <td>298개</td>\n",
       "      <td>513개</td>\n",
       "      <td>4원/g</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>5</th>\n",
       "      <td>샐러리 (1KG) 셀러리 CELERY 샐러드</td>\n",
       "      <td>4,000원</td>\n",
       "      <td>980개</td>\n",
       "      <td>231개</td>\n",
       "      <td>4원/g</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>6</th>\n",
       "      <td>손질샐러리 1팩 300g / 500g 스틱샐러리</td>\n",
       "      <td>4,900원</td>\n",
       "      <td>457개</td>\n",
       "      <td>215개</td>\n",
       "      <td>16원/g</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>7</th>\n",
       "      <td>[산지직송] 친환경 무농약 셀러리 (재 주문이 / 많은) 최상품 샐러리 3kg 5k...</td>\n",
       "      <td>18,500원</td>\n",
       "      <td>71개</td>\n",
       "      <td>139개</td>\n",
       "      <td>6원/g</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>8</th>\n",
       "      <td>무농약 셀러리 샐러리 양 미나리 3kg</td>\n",
       "      <td>19,900원</td>\n",
       "      <td>368개</td>\n",
       "      <td>32개</td>\n",
       "      <td>6원/g</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>9</th>\n",
       "      <td>당일수확 유기농 샐러리 신선초 500g 1kg 녹즙용 주스용 녹즙 채소 명일엽 셀러리</td>\n",
       "      <td>7,900원</td>\n",
       "      <td>26개</td>\n",
       "      <td>58개</td>\n",
       "      <td>15원/g</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>10</th>\n",
       "      <td>친환경 유기농 신선초(명일엽) 녹즙용 1kg/유기농 케일/무농약 셀러리</td>\n",
       "      <td>8,900원</td>\n",
       "      <td>267개</td>\n",
       "      <td>418개</td>\n",
       "      <td>8원/g</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>11</th>\n",
       "      <td>[삼현농장] 친환경 무농약 다용도 셀러리 2kg / 당일수확발송 (오전10시 주문분까지)</td>\n",
       "      <td>12,900원</td>\n",
       "      <td>3,637개</td>\n",
       "      <td>1,332개</td>\n",
       "      <td>6원/g</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>12</th>\n",
       "      <td>유기농 샐러리 500g 셀러리</td>\n",
       "      <td>4,900원</td>\n",
       "      <td>172개</td>\n",
       "      <td>64개</td>\n",
       "      <td>9원/g</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>13</th>\n",
       "      <td>공철표님의 싱싱한 무농약 셀러리/샐러리/양미나리 3kg</td>\n",
       "      <td>19,900원</td>\n",
       "      <td>368개</td>\n",
       "      <td>32개</td>\n",
       "      <td>6원/g</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>14</th>\n",
       "      <td>친환경 무농약 셀러리 3kg/5kg/양배추</td>\n",
       "      <td>18,900원</td>\n",
       "      <td>399개</td>\n",
       "      <td>88개</td>\n",
       "      <td>6원/g</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>15</th>\n",
       "      <td>[프레시팜] 국내산 셀러리 즙용 10kg 1박스</td>\n",
       "      <td>9,900원</td>\n",
       "      <td>3개</td>\n",
       "      <td>없음</td>\n",
       "      <td>0원/g</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>16</th>\n",
       "      <td>샐러리 10kg</td>\n",
       "      <td>24,800원</td>\n",
       "      <td>24개</td>\n",
       "      <td>55개</td>\n",
       "      <td>2원/g</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>17</th>\n",
       "      <td>채소습관 샐러리 스틱 100g x5팩</td>\n",
       "      <td>20,800원</td>\n",
       "      <td>153개</td>\n",
       "      <td>없음</td>\n",
       "      <td>208원/g</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>18</th>\n",
       "      <td>유기농 케일 신선초 비트 1kg 샐러리 500g 주스 쥬스 용 착즙 녹즙 즙 무농약 재료</td>\n",
       "      <td>4,900원</td>\n",
       "      <td>26개</td>\n",
       "      <td>85개</td>\n",
       "      <td>4원/g</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>19</th>\n",
       "      <td>유기농 무농약 샐러리 1kg 2kg</td>\n",
       "      <td>7,900원</td>\n",
       "      <td>4,184개</td>\n",
       "      <td>1,532개</td>\n",
       "      <td>7원/g</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>20</th>\n",
       "      <td>셀러리 샐러리 1kg 국산 1봉 1단 celery</td>\n",
       "      <td>3,500원</td>\n",
       "      <td>48개</td>\n",
       "      <td>32개</td>\n",
       "      <td>3원/g</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>21</th>\n",
       "      <td>절단 셀러리 500g</td>\n",
       "      <td>2,990원</td>\n",
       "      <td>3,977개</td>\n",
       "      <td>없음</td>\n",
       "      <td>5원/g</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>22</th>\n",
       "      <td>유기농 샐러리 500g 셀러리</td>\n",
       "      <td>4,900원</td>\n",
       "      <td>172개</td>\n",
       "      <td>62개</td>\n",
       "      <td>9원/g</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>23</th>\n",
       "      <td>[야채마루] 셀러리 샐러리 2kg   3kg   5kg - 신선한 셀러리를 당일배송으로</td>\n",
       "      <td>5,500원</td>\n",
       "      <td>229개</td>\n",
       "      <td>없음</td>\n",
       "      <td>2원/g</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>24</th>\n",
       "      <td>[팜포크] 다이어트에 좋은 친환경 무농약 샐러리 3kg, 5kg 샐러리 농장 산지직송</td>\n",
       "      <td>17,900원</td>\n",
       "      <td>없음</td>\n",
       "      <td>없음</td>\n",
       "      <td>5원/g</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>25</th>\n",
       "      <td>산정마을 국내산 샐러리 3kg</td>\n",
       "      <td>7,900원</td>\n",
       "      <td>499개</td>\n",
       "      <td>없음</td>\n",
       "      <td>2원/g</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>26</th>\n",
       "      <td>당근샐러리스틱 간편야채 380g</td>\n",
       "      <td>4,570원</td>\n",
       "      <td>1개</td>\n",
       "      <td>없음</td>\n",
       "      <td>12원/g</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>27</th>\n",
       "      <td>유기농 셀러리 1kg, 2kg 케일, 신선초, 명일엽, 녹즙채소</td>\n",
       "      <td>11,900원</td>\n",
       "      <td>14개</td>\n",
       "      <td>5개</td>\n",
       "      <td>11원/g</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>28</th>\n",
       "      <td>[조아쌈]무농약 녹즙케일 녹즙샐러리 짱아찌용 샐러리 2kg 당일수확, 당일배송</td>\n",
       "      <td>12,000원</td>\n",
       "      <td>3개</td>\n",
       "      <td>9개</td>\n",
       "      <td>6원/g</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>29</th>\n",
       "      <td>샐러리 (Celery) 1포기 1kg 내외</td>\n",
       "      <td>5,000원</td>\n",
       "      <td>42개</td>\n",
       "      <td>110개</td>\n",
       "      <td>5원/g</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>30</th>\n",
       "      <td>공철표님의 무농약 셀러리/샐러리/양미나리 5kg 3kg</td>\n",
       "      <td>18,620원</td>\n",
       "      <td>12개</td>\n",
       "      <td>없음</td>\n",
       "      <td>3원/g</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>31</th>\n",
       "      <td>유기농 녹즙 용 케일 1Kg (샐러리 신선초 비트 당근)</td>\n",
       "      <td>5,030원</td>\n",
       "      <td>19개</td>\n",
       "      <td>없음</td>\n",
       "      <td>5원/g</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>32</th>\n",
       "      <td>샐러리 1단 1kg</td>\n",
       "      <td>6,300원</td>\n",
       "      <td>110개</td>\n",
       "      <td>24개</td>\n",
       "      <td>6원/g</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>33</th>\n",
       "      <td>셀러리 녹즙 샐러리 5kg 3kg 2kg내외</td>\n",
       "      <td>24,900원</td>\n",
       "      <td>85개</td>\n",
       "      <td>3개</td>\n",
       "      <td>4원/g</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "</div>"
      ],
      "text/plain": [
       "                                                  상품명       가격     리뷰수  \\\n",
       "0                                         절단 셀러리 500g   2,990원      없음   \n",
       "1                                 친환경 무농약 셀러리 3kg/5kg  18,900원    399개   \n",
       "2                                     국내산 샐러리 2kg 5kg   5,500원  2,187개   \n",
       "3                                샐러리 3kg 5kg 10kg 셀러리  11,900원  1,731개   \n",
       "4     유기농 생 신선초 케일 샐러리 비트 1kg 주스용 쥬스용 착즙 녹즙 즙용 무농약 재료   4,900원    298개   \n",
       "5                            샐러리 (1KG) 셀러리 CELERY 샐러드   4,000원    980개   \n",
       "6                          손질샐러리 1팩 300g / 500g 스틱샐러리   4,900원    457개   \n",
       "7   [산지직송] 친환경 무농약 셀러리 (재 주문이 / 많은) 최상품 샐러리 3kg 5k...  18,500원     71개   \n",
       "8                               무농약 셀러리 샐러리 양 미나리 3kg  19,900원    368개   \n",
       "9     당일수확 유기농 샐러리 신선초 500g 1kg 녹즙용 주스용 녹즙 채소 명일엽 셀러리   7,900원     26개   \n",
       "10            친환경 유기농 신선초(명일엽) 녹즙용 1kg/유기농 케일/무농약 셀러리   8,900원    267개   \n",
       "11  [삼현농장] 친환경 무농약 다용도 셀러리 2kg / 당일수확발송 (오전10시 주문분까지)  12,900원  3,637개   \n",
       "12                                   유기농 샐러리 500g 셀러리   4,900원    172개   \n",
       "13                     공철표님의 싱싱한 무농약 셀러리/샐러리/양미나리 3kg  19,900원    368개   \n",
       "14                            친환경 무농약 셀러리 3kg/5kg/양배추  18,900원    399개   \n",
       "15                         [프레시팜] 국내산 셀러리 즙용 10kg 1박스   9,900원      3개   \n",
       "16                                           샐러리 10kg  24,800원     24개   \n",
       "17                               채소습관 샐러리 스틱 100g x5팩  20,800원    153개   \n",
       "18  유기농 케일 신선초 비트 1kg 샐러리 500g 주스 쥬스 용 착즙 녹즙 즙 무농약 재료   4,900원     26개   \n",
       "19                                유기농 무농약 샐러리 1kg 2kg   7,900원  4,184개   \n",
       "20                        셀러리 샐러리 1kg 국산 1봉 1단 celery   3,500원     48개   \n",
       "21                                        절단 셀러리 500g   2,990원  3,977개   \n",
       "22                                   유기농 샐러리 500g 셀러리   4,900원    172개   \n",
       "23   [야채마루] 셀러리 샐러리 2kg   3kg   5kg - 신선한 셀러리를 당일배송으로   5,500원    229개   \n",
       "24    [팜포크] 다이어트에 좋은 친환경 무농약 샐러리 3kg, 5kg 샐러리 농장 산지직송  17,900원      없음   \n",
       "25                                   산정마을 국내산 샐러리 3kg   7,900원    499개   \n",
       "26                                  당근샐러리스틱 간편야채 380g   4,570원      1개   \n",
       "27                유기농 셀러리 1kg, 2kg 케일, 신선초, 명일엽, 녹즙채소  11,900원     14개   \n",
       "28        [조아쌈]무농약 녹즙케일 녹즙샐러리 짱아찌용 샐러리 2kg 당일수확, 당일배송  12,000원      3개   \n",
       "29                            샐러리 (Celery) 1포기 1kg 내외   5,000원     42개   \n",
       "30                     공철표님의 무농약 셀러리/샐러리/양미나리 5kg 3kg  18,620원     12개   \n",
       "31                    유기농 녹즙 용 케일 1Kg (샐러리 신선초 비트 당근)   5,030원     19개   \n",
       "32                                         샐러리 1단 1kg   6,300원    110개   \n",
       "33                           셀러리 녹즙 샐러리 5kg 3kg 2kg내외  24,900원     85개   \n",
       "\n",
       "      구매건수    가격/g  \n",
       "0       없음    5원/g  \n",
       "1      88개    6원/g  \n",
       "2   1,102개    2원/g  \n",
       "3     166개    3원/g  \n",
       "4     513개    4원/g  \n",
       "5     231개    4원/g  \n",
       "6     215개   16원/g  \n",
       "7     139개    6원/g  \n",
       "8      32개    6원/g  \n",
       "9      58개   15원/g  \n",
       "10    418개    8원/g  \n",
       "11  1,332개    6원/g  \n",
       "12     64개    9원/g  \n",
       "13     32개    6원/g  \n",
       "14     88개    6원/g  \n",
       "15      없음    0원/g  \n",
       "16     55개    2원/g  \n",
       "17      없음  208원/g  \n",
       "18     85개    4원/g  \n",
       "19  1,532개    7원/g  \n",
       "20     32개    3원/g  \n",
       "21      없음    5원/g  \n",
       "22     62개    9원/g  \n",
       "23      없음    2원/g  \n",
       "24      없음    5원/g  \n",
       "25      없음    2원/g  \n",
       "26      없음   12원/g  \n",
       "27      5개   11원/g  \n",
       "28      9개    6원/g  \n",
       "29    110개    5원/g  \n",
       "30      없음    3원/g  \n",
       "31      없음    5원/g  \n",
       "32     24개    6원/g  \n",
       "33      3개    4원/g  "
      ]
     },
     "execution_count": 13,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "# 그램당 가격 추출하기\n",
    "GramPerPrice = []\n",
    "for i in range(len(df1)):\n",
    "    res = plist[i] // gram_list[i]\n",
    "    GramPerPrice.append(str(res)+'원/g')\n",
    "df1['가격/g'] = GramPerPrice\n",
    "del df1['무게당 가격']\n",
    "df1"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.7.6"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 4
}
